### ISSUE TITLE
Generalize the inbound supplychain document pipeline

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#120]
yes, RHT is CSAF, but... others do otherwise.
hopefully also help us generalize the fetch/ingest/store pipeline across formats.
so we're not having to mirror osv_walker like csaf_walker like ghsa_walker like msftadvisory_walker, like...
Walker<CSAF, Http, S3>::new()...
Walker<OSV, FileSystem, FileSystem>::new()
or whatnot
Walker<FORMAT, SOURCE, STORAGE_DEST>

**Comment by ctron** [comment]
Assuming you're talking about "importing" data, that should go into the "importer" crate. There's an enum for that, supporting multiple variants (not too many at the this point). https://github.com/trustification/trustify/blob/a710806ad9b8ceb5b962c04b693fdcba5c929bff/importer/src/lib.rs#L11-L15

It's just using "walkers" to implement those importers.

I think adding more sources, we should add more importers. Using "walkers" if it makes sense. And I am not sure it always does. I am not sure sure about using generics for that, because they can be pretty painful at times. And unless we expect people to add arbitrary importers themselves, traits add an unnecessary complexity over an enum pattern like that.

**Comment by ctron** [comment]
so far that process was:

* endpoint -> service -> database + fs
* importer -> service -> database + fs

The both endpoint and importer had very little (to none) logic there.

**Comment by bobmcwhirter** [comment]
Ah, that works!
