### ISSUE TITLE
For relevant documents, remove `location` as a defining part of a composite key

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#160]
Just SHAs.

**Comment by ctron** [comment]
What if the same document comes in from two different sources? For example: company A publishes an SBOM, and company B re-publishes that as part of their own solution. How could we distinguish those? Assuming I would want to clean up SBOMs from company B, how could I find out what came in from them?

**Comment by ctron** [comment]
Because I just noticed this on the advisories: All functionality seems to work with an "identifier". Which seems to be the "document id" (e.g. RHSA…), and deriving information on that.

Dropping the digest from this leads to the ability of one source overriding statements of the other source.

Keeping the digest, seems to lead to the result that we have a lot of statements that are no longer relevant.

I believe that keeping the source/location as part of the document ID  would solve both cases.

**Comment by bobmcwhirter** [comment]
Keep only SHA not dropping the digest.

**Comment by bobmcwhirter** [comment]
Lemme drink some coffee and think some more

**Comment by bobmcwhirter** [comment]
Yeah, so I think always keep the SHA digest. Either using it as the PK for all related statements or the current auto-increment PK (which is tied 1:1 to the SHA).

I do agree knowing the 'source' of some document could be useful, but may also be optional, in terms of "where the document was sitting prior to ingesting".

But also knowing the `source` of the document from it's... internal data? externally-applied signatures?

e.g., regardless *where in terms of location* the document came from (MySpace, USB drive), if it's signed by Red Hat, it's a Red Hat-sourced document.

**Comment by ctron** [comment]
> e.g., regardless _where in terms of location_ the document came from (MySpace, USB drive), if it's signed by Red Hat, it's a Red Hat-sourced document.

I think we need a lot more clarity around our management of documents. When I delete a source (e.g. "CSAFs from Acme Inc"), how can I remove them from my inventory? If they published a Red Hat SBOM as part of their product, will that delete the Red Hat SBOM which came in from the RH source?
