### ISSUE TITLE
Explore alternative table structure for packages

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#178]
Right now ingesting SBOMs slow (see #165). A first investigation shows that a lot of traffic happens on the tables around packages (package versions, qualified packages, …). I think it makes sense exploring alternative ways of storing this information.

Ideas:

* flat table: package url, split up, qualifiers as JSON field (?)
* [ltree](https://www.postgresql.org/docs/16/ltree.html): might not work as we don't have actual "labels"
* using values as primary key (vs auto-increments), not sure this works

One aspect of this is also that question if a package "belongs" to an SBOM. Or is just referenced by an SBOM. The question is, what will happen when an SBOM gets deleted. IMHO this should remove all packages stored in the database as well.

**Comment by bobmcwhirter** [comment]
So far I've been considering packages to *not* belong to an SBOM.

This allows folks to navigate from the root -> package -> what else includes/references/uses it across all of the SBOMs we have.

log4j -> log4j@1.2.3 -> { quarkus-1.2, eap-9.7, ...}

The reason for the qualifiers to be outside of the base package is mostly due to not having to canonicalize or care about order of qualifiers, or to be able to do searches based on subsets of qualifiers.  Likewise, keeping versions separate allows us to know that log4j@1.2.3 and log4j@2.3 are both variants of the same Platonic package.

We could fully denormalize and let a qualified package version be a single row in a single DB, but then we are somewhat back to having to find a different way to group variants back together.

**Comment by ctron** [comment]
> So far I've been considering packages to _not_ belong to an SBOM.

That's an interesting aspect. I didn't fully check, but I noticed some "sbom_id" field, at least once. We also have the requirements of the "document describes" entrypoint, which not all SBOMs have. So maybe we do need the idea of an SBOM, and the fact that packages can be contained in one. But that's a topic for another issue/discussion.

> We could fully denormalize and let a qualified package version be a single row in a single DB, but then we are somewhat back to having to find a different way to group variants back together.

Yes, that's the downside. And we would have a lot of duplicate values in the table as well (increasing storage). Maybe an index could help, maybe `ltree`, … I don't know. But that's the whole point: measure, don't guess!

**Comment by bobmcwhirter** [comment]
A relationship between packages is an assertion tied to an SBOM. 

Many SBOMs can make different assertions.

**Comment by ctron** [comment]
So in SPDX terms: we have a global pool of packages and a per-SBOM table (not DB table) of package relationships?

**Comment by bobmcwhirter** [comment]
Yes

**Comment by ctron** [comment]
I think we solved this some time ago. If not, we can re-open.
