### ISSUE TITLE
Build docs, see what shouldn't be as public as it is.

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#24]

**Comment by helio-frota** [comment]
> Build docs, 

> see what shouldn't be as public as it is

Hi @bobmcwhirter you mean to build locally? If yes then can we close the issue? since we already closed the other related #17 

if not , I'm afraid because if we have plans to push docs to gh-pages or the main repo we may encounter git-sizes-issues as I found some discussions about that here: https://www.reddit.com/r/rust/comments/wy3j50/psa_if_youre_using_ghpages_to_host_your/

thanks

**Comment by bobmcwhirter** [comment]
Yah, mostly meant `cargo doc --open` locally and then review.

Useful to know:

1. what isn't documented
2. what isn't documented but shouldn't even appear in the docs, meaning we should adjust the `pub` settings of modules/structs/fns.

**Comment by helio-frota** [comment]
thank you :+1:
