### ISSUE TITLE
Provide a Container image that can be used to start the server

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#313]

**Comment by ctron** [comment]
This was closed by release: `0.1.0-alpha.3`: https://github.com/trustification/trustify/releases/tag/v0.1.0-alpha.3

You can run a container using e.g.:

```bash
podman run -ti --rm ghcr.io/trustification/trustd:0.1.0-alpha.3 help
```

There's one caveat: The embedded PostgreSQL mode does not work due to missing libraries inside the container. However, I am not sure it makes that much sense to have the full functionality of downloading and running an psql database inside the container is the best idea. If that's the case, we should come up with an additional `-pm` mode container variant.
