### ISSUE TITLE
Ingesting an OSV document doesn't seem to create a vulnerability

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#531]
When ingesting an OSV document, it creates the advisory, vulnerabilities for the advisory, but it doesn't create a vulnerability.

**Comment by ctron** [comment]
Ok, that's weird. Ingesting an OSV document and then:

* Calling `ctx.graph.get_vulnerabilities(())`  gives zero vulnerabilities
* Calling `ctx.graph.get_vulnerability("CVE-2021-32714", ())` returns the one

**Comment by ctron** [comment]
It looks like as if `get_vulnerability` returns an `advisory_vulnerability` if no actual `vulnerability` was found. While `get_vulnerabilities` doesn't do that.

That's confusing IMO.

**Comment by ctron** [comment]
There's a draft PR with a test for this: https://github.com/trustification/trustify/pull/532 (which is currently failing)

**Comment by ctron** [comment]
Looks like the same is true for CSAF.

**Comment by bobmcwhirter** [comment]
The `graph.get_vulnerability` should be deleted.

Since the vulnerabilities are natural-key data, ingesting an OSV only creates advisory-related things which reference the vulnerability identifier, _even if it does not yet exist in the vulnerability table_.

When CVE ingests, it'll back-fill.

Given all of that, though, we do want to consider any vulnerability identifiers mentioned in advisories as "existing" from /api/v1/vulnerability POV, even if not backfilled with data from CVERecords yet.

The VulnerabilityService does the right thing (in theory).

**Comment by ctron** [comment]
Should be closed by #532
