### ISSUE TITLE
Error 401 occurs on PM mode

### ISSUE THREAD

**Issue by mrrajan** [trustification/trustify#689]
When trying to access trustify with PM mode `cargo run --bin trustd`, API calls errors with 401.
Please find the logs below:
[pm_mode.txt](https://github.com/user-attachments/files/16635535/pm_mode.txt)

**Comment by jcrossley3** [comment]
PM Mode really only "works" within a browser, interacting with the Javascript app, transparently authenticating through an embedded OIDC server. If you're trying to access the API directly via curl/wget/httpie/swagger-ui, you'll have better luck like so:
```
AUTH_DISABLED=true cargo run --bin trustd
```

**Comment by jcrossley3** [comment]
Does it seem random? It may be a problem with the embedded OIDC server, which is really just a hack that'll never be used in production.

If you're just looking to test the behavior of the app, irrespective of auth, I recommend `AUTH_DISABLED=true`.

**Comment by ctron** [comment]
"Unable to connect" is bit generic. There should be more information in the browser's developer console about the actual cause.

The UI fetches an access token and needs to refresh once it expires. If the UI uses an invalid token, you'll get 401.

Instead of just disabling authentication, we should find the cause for this. As this might have an impact on the actual system, independent of "pm mode".

**Comment by ctron** [comment]
I just tried this out. And it works as expected. Do you have any details that could help reproduce?

**Comment by helio-frota** [comment]
thanks for the follow up 

I remember when it was reported and I guess it was "double-click" close/reopen or something

![2024-08-28_07-31](https://github.com/user-attachments/assets/582b38c1-76c1-4be8-81ec-60ea94b2b60d)

@mrrajan can you please confirm? thanks!

**Comment by mrrajan** [comment]
I couldnt reproduce the issue with the latest commit - Not sure what went wrong before! I hope we can close it and reopen if needed.
