### ISSUE TITLE
Advisory - "revision" add filter

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#968]
V1 UI can filter Advisories by "Revision" date.

We need the following filter to work:

```shell
q=revision>FROM_DATE&revision<TO_DATE
```

![Screenshot From 2024-11-05 13-18-00_2](https://github.com/user-attachments/assets/bfff679c-e863-4e9a-8457-ca67f33f3ac6)

**Comment by carlosthe19916** [comment]
The request is to make the filter work on `/api/v1/advisory`

**Comment by jcrossley3** [comment]
@carlosthe19916 if it's important, we can trivially alias `modified` to `revision` so that either will work.

**Comment by carlosthe19916** [comment]
> @carlosthe19916 if it's important, we can trivially alias `modified` to `revision` so that either will work.

Thanks but I think it is fine to use `modified` without adding more things to the rest endpoint. I was just ignoring that the `modified` field was actually what we used to call `revision` in V1, so it was just my ignorance on matching terms. 

Good to know we can add aliases though. We might need it in the future.

**Comment by jcrossley3** [comment]
Cool. Since you're comparing dates, keep in mind that we support "human date specs" so [some of these examples](https://github.com/trustification/trustify/blob/68d08bc52e6e65ac8d352ad524904df7a20d2cf8/common/src/db/query/filter.rs#L489-L524) may save you some client-side date math, e.g. `q=modified>10 days ago` (url-encoded, of course)
